In [1]:
import numpy as np
np.array([[0,1],[0,5]])

array([[0, 1],
       [0, 5]])

In [5]:
np.sum([[0,1],[0,5]],axis=0)

array([0, 6])

In [9]:
np.cumsum([[0,1],[0,5]])

array([0, 1, 1, 6], dtype=int32)

In [10]:
np.array(["Karachi,""Lahore"])

array(['Karachi,Lahore'], dtype='<U14')

In [15]:
np.array([[2,3],[5,8]]).shape

(2, 2)

In [25]:
num=7/3
np.remainder(7,3)

1

In [13]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])

In [28]:
arr[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
sample_array=np.array([1,2,3])

In [26]:
ones=np.ones_like([1,2,3])

In [27]:
ones

array([1, 1, 1])